name: publish to docker

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rodrigo8torres4/volume_calculator:$(date +%s)
      
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/volume_calculator:$(date +%s)
  
